### PR TITLE
Also add gherkin.formatter.Argument

### PR DESCRIPTION
**Pull request by jglick**
Extends #12 a bit.

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
@jglick looks OK.  Do we also need to add enums -  `gherkin.formatter.model.Row$DiffType` is referenced from Row?

**Comment by jglick** [comment]
Right, we need not list `enum`s.

FTR @benjamin_ruhlmann says

> I installed the snapshot and it works perfectly.

**Comment by jglick** [comment]
so @reviewbybees done FWIW

**Comment by oleg-nenashev** [comment]
@jtnord would be nice to ship it this week

**Comment by jtnord** [comment]
Thanks Jesse

**Pull request merged**
